project:
  type: website
  output-dir: docs
  # resources: 
  #   - "resume.pdf"

email-obfuscation: javascript

lang: en-US

website:
  favicon: icon.png
  twitter-card: true
  site-url: https://nikola-grubor.github.io
  title: "Nikola N. Grubor"
  navbar:
    tools:
      - icon: twitter
        href: ""
      - icon: github
        href: https://github.com/nikola-grubor
      - icon: linkedin
        href: https://www.linkedin.com/in/herr-grubor/
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: myblog/index.qmd
        text: Blog

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

